### ISSUE TITLE
fatal error when activating plugin

### ISSUE THREAD

**Issue by hillfingerr** [Codeinwp/woocommerce-product-addon#115]
### Description

I have version 6.1.1 of wordpress and 7.5 of woocommerce and when I try to activate the plugin I get this:

Plugin could not be activated because it triggered a fatal error.

Fatal error: Uncaught Error: Call to undefined function error_log() in wp-includes/class-wpdb.php:1602 Stack trace: #0 wp-includes/class-wpdb.php(2128): wpdb->print_error() #1 wp-content/plugins/woocommerce-product-addon/classes/plugin.class.php(841): wpdb->query() #2 wp-content/plugins/woocommerce-product-addon/classes/plugin.class.php(657): NM_PersonalizedProduct::ppom_install_demo_meta() #3 wp-includes/class-wp-hook.php(308): NM_PersonalizedProduct::activate_plugin() #4 wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() #5 wp-includes/plugin.php(517): WP_Hook->do_action() #6 wp-admin/plugins.php(194): do_action() #7 {main} thrown in wp-includes/class-wpdb.php on line 1602 

### Step-by-step reproduction instructions

go to plugins - PPOM for WooCommerce
click activate button

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by selul** [comment]
Thank you for reporting the issue @hillfingerr.

Upon reviewing the error message, we believe that there might be a misunderstanding or a possible misconfiguration in your environment. The error_log() function is a core PHP function, which means it is built-in and should be available by default. It is highly unlikely for this function to be undefined in a standard PHP installation.

Please ensure that your PHP installation is up-to-date and that no custom configurations or third-party extensions are interfering with the standard PHP functions. You can also ask your hosting company about this, they might be better equipped to debug this.
