### ISSUE TITLE
fatal error related tsdk_utmify

### ISSUE THREAD

**Issue by mskapusuz** [Codeinwp/woocommerce-product-addon#24]
An error is occurring on the dashboard and that prevents opening of the the PPOM dashboard

**Error:**
```
[02-Sep-2022 22:46:16 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function tsdk_utmify() in /Users/MASKED/Projects/ppom-reproduce-error-1/wp-content/plugins/woocommerce-product-addon/inc/admin.php:656
Stack trace:
#0 /Users/MASKED/Projects/ppom-reproduce-error-1/wp-includes/class-wp-hook.php(307): ppom_admin_update_pro_notice('')
#1 /Users/MASKED/Projects/ppom-reproduce-error-1/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#2 /Users/MASKED/Projects/ppom-reproduce-error-1/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#3 /Users/MASKED/Projects/ppom-reproduce-error-1/wp-content/plugins/woocommerce-product-addon/classes/admin.class.php(160): do_action('ppom_pdf_settin...')
#4 /Users/MASKED/Projects/ppom-reproduce-error-1/wp-includes/class-wp-hook.php(307): NM_PersonalizedProduct_Admin->product_meta('')
#5 /Users/MASKED/Projects/ppom-reproduce-error-1/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#6 /Users/MASKED/Projects/ppom-reproduce-error-1/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#7 /Users/MASKED/Projects/ppom-reproduce-error-1/wp-admin/admin.php(259): do_action('woocommerce_pag...')
#8 /Users/MASKED/.composer/vendor/laravel/valet/server.php(234): require('/Users/mskapusu...')
#9 {main}
  thrown in /Users/MASKED/Projects/ppom-reproduce-error-1/wp-content/plugins/woocommerce-product-addon/inc/admin.php on line 656

```

![Screen Shot 2022-09-03 at 01 49 04](https://user-images.githubusercontent.com/25361626/188243885-9756290b-3bd3-4560-9e17-0a63d92dffc8.png)

I could reproduce it just now on my end.

**Reproducing steps:**

1. Install&Activate WC
2. Install&Activate PPOM Free (v30.1.3)
3. Make sure your theme is different than Neve v3.3.7 (You should have any theme (if you have Neve, make sure the version is lower than v3.3.7))
4. Visit WP Admin -> WooCommerce -> PPOM Fields, you will see the page is not opened.

Firstly, the issue reported here: https://wordpress.org/support/topic/preloader-doesnt-disappear/

**Comment by mskapusuz** [comment]
cc: @selul
