### ISSUE TITLE
Wordpress fatal error after upgrade to 32.0.10

### ISSUE THREAD

**Issue by oleva** [Codeinwp/woocommerce-product-addon#253]
### Description

After update to latest PPOM 32.0.10 from 32.0.09 I get PHP fatal error for /wp-includes/capabilities.php:877. I was unable to access Wordpress admin panel, the error was thrown on login to admin.

I have the same (PPOM) plugin installed on other sites where the upgrade did not cause this, so it might be a conflict issue. But it definetly happened after the upgrade. I installed now the older version and everything seems to work,

Wordpress version: 6.4.3
PHP 8.2
Open Litespeed server

Here's a list of active plugins:

```
+------------------------------------------+--------+------------------------------+---------+
| name                                     | status | update                       | version |
+------------------------------------------+--------+------------------------------+---------+
| advanced-woo-search                      | active | none                         | 3.01    |
| antispam-bee                             | active | none                         | 2.11.5  |
| woocommerce-bulk-editor                  | active | version higher than expected | 2.1.1   |
| better-search-replace                    | active | none                         | 1.4.5   |
| taxonomy-terms-order                     | active | none                         | 1.8     |
| contact-form-7                           | active | none                         | 5.8.7   |
| coupons-plus                             | active | none                         | 2.0.1   |
| customer-reviews-woocommerce             | active | none                         | 5.41.0  |
| elementor                                | active | none                         | 3.19.4  |
| envato-market                            | active | none                         | 2.0.11  |
| webtoffee-gdpr-cookie-consent            | active | none                         | 2.4.0   |
| litespeed-cache                          | active | none                         | 6.1     |
| mailchimp-for-woocommerce                | active | none                         | 3.6     |
| nextend-facebook-connect                 | active | none                         | 3.1.13  |
| nextend-social-login-pro                 | active | none                         | 3.1.13  |
| woocommerce-pdf-invoices-packing-slips   | active | none                         | 3.7.7   |
| woocommerce-product-addon                | active | available                    | 32.0.9  |
| redux-framework                          | active | none                         | 4.4.13  |
| google-site-kit                          | active | none                         | 1.121.0 |
| revslider                                | active | none                         | 6.6.16  |
| better-wp-security                       | active | none                         | 9.3.1   |
| stop-user-enumeration                    | active | none                         | 1.4.9   |
| svg-support                              | active | none                         | 2.5.5   |
| themesky                                 | active | none                         | 1.0.9   |
| woocommerce                              | active | none                         | 8.6.1   |
| woocommerce-google-analytics-integration | active | none                         | 1.8.14  |
| addon-woocommerce-ppom-plugin            | active | none                         | 1.0.0   |
| woo-carrier-agents                       | active | none                         | 1.7.1   |
| wc-paytrail                              | active | none                         | 2.5.1   |
| wc-smartship                             | active | none                         | 2.0.2   |
| woocommerce-multistore                   | active | version higher than expected | 5.2.7   |
| wordpress-seo                            | active | none                         | 22.1    |
+------------------------------------------+--------+------------------------------+---------+
```

I can check the possible plugin conflicts tomorrow and let you know if I found any errors there!

These are the plugins that might be giving the error, because they are different from the one that is working:

coupons-plus
nextend-facebook-connect
nextend-social-login-pro
stop-user-enumeration
woocommerce-google-analytics-integration
woo-carrier-agents
wc-paytrail
wc-smartship

### Step-by-step reproduction instructions

Update / auto-update PPOM plugin to 32.0.10

### Screenshots, screen recording, code snippet or Help Scout ticket

```
2024-02-29 12:29:58.068077 [NOTICE] [327245] [172.70.46.201:17590:HTTP2-1#domain.do] [STDERR] PHP Fatal error:  Uncaught Error: Call to undefined function wp_get_current_user() in /home/client/webapps/domain/wordpress/wp-includes/capabilities.php:877
  thrown in /home/client/webapps/domain/wordpress/wp-includes/capabilities.php on line 877
#7 {main}
#6 /home/client/webapps/domain/wordpress/wp-admin/update-core.php(10): require_once('...')
#5 /home/client/webapps/domain/wordpress/wp-admin/admin.php(34): require_once('...')
#4 /home/client/webapps/domain/wordpress/wp-load.php(50): require_once('...')
#3 /home/client/webapps/domain/wordpress/wp-config.php(97): require_once('...')
#2 /home/client/webapps/domain/wordpress/wp-settings.php(473): include_once('...')
#1 /home/client/webapps/domain/wordpress/wp-content/plugins/woocommerce-product-addon/woocommerce-product-addon.php(101): NM_PersonalizedProduct_Admin->__construct()
#0 /home/client/webapps/domain/wordpress/wp-content/plugins/woocommerce-product-addon/classes/admin.class.php(65): current_user_can()
```

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://wordpress.org/support/topic/fatal-error-4639/ (+3 replies on the same issue)

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://wordpress.org/support/topic/warning-after-updates-2/

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://secure.helpscout.net/conversation/2525575666/406444?viewId=931544

**Comment by AndreeaCristinaRadacina** [comment]
I tested and I still get this error:
<img width="1680" alt="image" src="https://github.com/Codeinwp/woocommerce-product-addon/assets/86592992/9222df81-8324-4527-831b-afef6e753820">
Also, no fields are visible.

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://secure.helpscout.net/conversation/2525856446/406515?viewId=931544
